# Workflow will build a new PyCDK image based on the
# latest version from AWS.

name: Build the latest CDK

# Controls when the workflow will run
on:
  schedule:
    - cron: '00 15 * * *'
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Latest Github Release Tag
        uses: rez0n/actions-github-release@v1.7
        id: cdk_release
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "aws/aws-cdk"
          type: "latest"

      # Remove the v from version tag
      - name: CDK Version From Tag
        id: get-ver
        run: |
          ver=$(echo ${{steps.cdk_release.outputs.release}} | cut -dv -f2)
          echo "::set-output name=cdkver::$ver"
      # Debug output the CDK version
      - name: CDK Version From Tag
        env: 
          VER: ${{ steps.get-ver.outputs.cdkver }}
        run: echo Latest CDK Version $VER

      #Start Docker Build
      - name: Log in to the Container registry
        uses: docker/login-action@v1.12.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{steps.get-ver.outputs.cdkver}}
            type=raw,value=${{steps.cdk_release.outputs.release}}
            type=raw,value=latest
      - name: Build and push Docker image
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: CDK_VERSION=${{ steps.get-ver.outputs.cdkver }}
